import open3d as o3d
import numpy as np
from utils import flength_offset2intrinsic_matrix, quaternion2rotation_matrix, translation2translation_matrix, initialize_camera

txt_path = "" # PUT your txt folder path generated by COLMAP
intrinsic_path = f"{txt_path}/cameras.txt"
extrinsic_path = f"{txt_path}/images.txt"

o3d.visualization.webrtc_server.enable_webrtc()

with open(intrinsic_path, "r") as i, open(extrinsic_path, "r") as e:
    iline = i.readline()
    while iline.startswith("#"):
        iline = i.readline()
    _, __, width, height, fx, fy, px, py, *_ = iline.split(' ')
    intrinsic = flength_offset2intrinsic_matrix(fx=fx, fy=fy, px=px, py=py)

    extrinsics = []
    eline = e.readline()
    while eline != "":
        if eline.endswith('.png\n'):
            _, qw, qx, qy, qz, tx, ty, tz, __, name = eline.split(' ')
            R = quaternion2rotation_matrix(qw=float(qw), qx=float(qx), qy=float(qy), qz=float(qz))
            t = translation2translation_matrix(tx=tx, ty=ty, tz=tz)
            extrinsic = np.vstack((np.hstack((R, t)), np.array([0, 0, 0, 1])))
            extrinsics.append(extrinsic)
        eline = e.readline()
    
    cameras = []
    for extrinsic in extrinsics:
        camera = initialize_camera(intrinsic=intrinsic, extrinsic=extrinsic, width=int(width), height=int(height), scale=1)
        cameras.append(camera)

    o3d.visualization.draw(cameras)